// Mocks generated by Mockito 5.4.6 from annotations
// in openvine/test/integration/proofmode_recording_integration_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;
import 'dart:typed_data' as _i4;

import 'package:mockito/mockito.dart' as _i1;
import 'package:openvine/services/proofmode_session_service.dart' as _i2;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

/// A class which mocks [ProofModeSessionService].
///
/// See the documentation for Mockito's code generation for more information.
class MockProofModeSessionService extends _i1.Mock
    implements _i2.ProofModeSessionService {
  MockProofModeSessionService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  bool get hasActiveSession =>
      (super.noSuchMethod(
            Invocation.getter(#hasActiveSession),
            returnValue: false,
          )
          as bool);

  @override
  bool get isRecording =>
      (super.noSuchMethod(Invocation.getter(#isRecording), returnValue: false)
          as bool);

  @override
  _i3.Future<void> ensureInitialized() =>
      (super.noSuchMethod(
            Invocation.method(#ensureInitialized, []),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<String?> startSession({
    int? frameSampleRate = 1,
    int? maxFrameHashes = 1000,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#startSession, [], {
              #frameSampleRate: frameSampleRate,
              #maxFrameHashes: maxFrameHashes,
            }),
            returnValue: _i3.Future<String?>.value(),
          )
          as _i3.Future<String?>);

  @override
  _i3.Future<void> captureFrame(_i4.Uint8List? frameData) =>
      (super.noSuchMethod(
            Invocation.method(#captureFrame, [frameData]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> pauseRecording() =>
      (super.noSuchMethod(
            Invocation.method(#pauseRecording, []),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> resumeRecording() =>
      (super.noSuchMethod(
            Invocation.method(#resumeRecording, []),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> endSession() =>
      (super.noSuchMethod(
            Invocation.method(#endSession, []),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> startRecordingSegment() =>
      (super.noSuchMethod(
            Invocation.method(#startRecordingSegment, []),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> stopRecordingSegment() =>
      (super.noSuchMethod(
            Invocation.method(#stopRecordingSegment, []),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> addFrameHash(_i4.Uint8List? frameData) =>
      (super.noSuchMethod(
            Invocation.method(#addFrameHash, [frameData]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> recordInteraction(
    String? type,
    double? x,
    double? y, {
    double? pressure,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #recordInteraction,
              [type, x, y],
              {#pressure: pressure},
            ),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<_i2.ProofManifest?> finalizeSession(String? finalVideoHash) =>
      (super.noSuchMethod(
            Invocation.method(#finalizeSession, [finalVideoHash]),
            returnValue: _i3.Future<_i2.ProofManifest?>.value(),
          )
          as _i3.Future<_i2.ProofManifest?>);

  @override
  _i3.Future<void> cancelSession() =>
      (super.noSuchMethod(
            Invocation.method(#cancelSession, []),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);
}
