// Mocks generated by Mockito 5.4.6 from annotations
// in openvine/test/widgets/share_video_menu_todo_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;

import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i6;
import 'package:nostr_sdk/nostr_sdk.dart' as _i7;
import 'package:openvine/services/auth_service.dart' as _i3;
import 'package:openvine/services/bookmark_service.dart' as _i4;
import 'package:openvine/services/nostr_service_interface.dart' as _i2;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeINostrService_0 extends _i1.SmartFake implements _i2.INostrService {
  _FakeINostrService_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeAuthService_1 extends _i1.SmartFake implements _i3.AuthService {
  _FakeAuthService_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [BookmarkService].
///
/// See the documentation for Mockito's code generation for more information.
class MockBookmarkService extends _i1.Mock implements _i4.BookmarkService {
  MockBookmarkService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.INostrService get nostrService =>
      (super.noSuchMethod(
            Invocation.getter(#nostrService),
            returnValue: _FakeINostrService_0(
              this,
              Invocation.getter(#nostrService),
            ),
          )
          as _i2.INostrService);

  @override
  _i3.AuthService get authService =>
      (super.noSuchMethod(
            Invocation.getter(#authService),
            returnValue: _FakeAuthService_1(
              this,
              Invocation.getter(#authService),
            ),
          )
          as _i3.AuthService);

  @override
  List<_i4.BookmarkItem> get globalBookmarks =>
      (super.noSuchMethod(
            Invocation.getter(#globalBookmarks),
            returnValue: <_i4.BookmarkItem>[],
          )
          as List<_i4.BookmarkItem>);

  @override
  List<_i4.BookmarkSet> get bookmarkSets =>
      (super.noSuchMethod(
            Invocation.getter(#bookmarkSets),
            returnValue: <_i4.BookmarkSet>[],
          )
          as List<_i4.BookmarkSet>);

  @override
  bool get isInitialized =>
      (super.noSuchMethod(Invocation.getter(#isInitialized), returnValue: false)
          as bool);

  @override
  _i5.Future<void> initialize() =>
      (super.noSuchMethod(
            Invocation.method(#initialize, []),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<bool> addVideoToGlobalBookmarks(
    String? videoEventId, {
    String? relay,
    String? petname,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #addVideoToGlobalBookmarks,
              [videoEventId],
              {#relay: relay, #petname: petname},
            ),
            returnValue: _i5.Future<bool>.value(false),
          )
          as _i5.Future<bool>);

  @override
  _i5.Future<bool> addToGlobalBookmarks(_i4.BookmarkItem? item) =>
      (super.noSuchMethod(
            Invocation.method(#addToGlobalBookmarks, [item]),
            returnValue: _i5.Future<bool>.value(false),
          )
          as _i5.Future<bool>);

  @override
  _i5.Future<bool> removeFromGlobalBookmarks(_i4.BookmarkItem? item) =>
      (super.noSuchMethod(
            Invocation.method(#removeFromGlobalBookmarks, [item]),
            returnValue: _i5.Future<bool>.value(false),
          )
          as _i5.Future<bool>);

  @override
  bool isInGlobalBookmarks(String? itemId, String? type) =>
      (super.noSuchMethod(
            Invocation.method(#isInGlobalBookmarks, [itemId, type]),
            returnValue: false,
          )
          as bool);

  @override
  bool isVideoBookmarkedGlobally(String? videoEventId) =>
      (super.noSuchMethod(
            Invocation.method(#isVideoBookmarkedGlobally, [videoEventId]),
            returnValue: false,
          )
          as bool);

  @override
  _i5.Future<_i4.BookmarkSet?> createBookmarkSet({
    required String? name,
    String? description,
    String? imageUrl,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#createBookmarkSet, [], {
              #name: name,
              #description: description,
              #imageUrl: imageUrl,
            }),
            returnValue: _i5.Future<_i4.BookmarkSet?>.value(),
          )
          as _i5.Future<_i4.BookmarkSet?>);

  @override
  _i5.Future<bool> addToBookmarkSet(String? setId, _i4.BookmarkItem? item) =>
      (super.noSuchMethod(
            Invocation.method(#addToBookmarkSet, [setId, item]),
            returnValue: _i5.Future<bool>.value(false),
          )
          as _i5.Future<bool>);

  @override
  _i5.Future<bool> removeFromBookmarkSet(
    String? setId,
    _i4.BookmarkItem? item,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#removeFromBookmarkSet, [setId, item]),
            returnValue: _i5.Future<bool>.value(false),
          )
          as _i5.Future<bool>);

  @override
  _i5.Future<bool> updateBookmarkSet({
    required String? setId,
    String? name,
    String? description,
    String? imageUrl,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#updateBookmarkSet, [], {
              #setId: setId,
              #name: name,
              #description: description,
              #imageUrl: imageUrl,
            }),
            returnValue: _i5.Future<bool>.value(false),
          )
          as _i5.Future<bool>);

  @override
  _i5.Future<bool> deleteBookmarkSet(String? setId) =>
      (super.noSuchMethod(
            Invocation.method(#deleteBookmarkSet, [setId]),
            returnValue: _i5.Future<bool>.value(false),
          )
          as _i5.Future<bool>);

  @override
  _i4.BookmarkSet? getBookmarkSetById(String? setId) =>
      (super.noSuchMethod(Invocation.method(#getBookmarkSetById, [setId]))
          as _i4.BookmarkSet?);

  @override
  bool isInBookmarkSet(String? setId, String? itemId, String? type) =>
      (super.noSuchMethod(
            Invocation.method(#isInBookmarkSet, [setId, itemId, type]),
            returnValue: false,
          )
          as bool);

  @override
  List<_i4.BookmarkSet> getBookmarkSetsContainingVideo(String? videoEventId) =>
      (super.noSuchMethod(
            Invocation.method(#getBookmarkSetsContainingVideo, [videoEventId]),
            returnValue: <_i4.BookmarkSet>[],
          )
          as List<_i4.BookmarkSet>);

  @override
  String getVideoBookmarkSummary(String? videoEventId) =>
      (super.noSuchMethod(
            Invocation.method(#getVideoBookmarkSummary, [videoEventId]),
            returnValue: _i6.dummyValue<String>(
              this,
              Invocation.method(#getVideoBookmarkSummary, [videoEventId]),
            ),
          )
          as String);

  @override
  _i5.Future<List<_i7.Event>> getMyPublishedEvents() =>
      (super.noSuchMethod(
            Invocation.method(#getMyPublishedEvents, []),
            returnValue: _i5.Future<List<_i7.Event>>.value(<_i7.Event>[]),
          )
          as _i5.Future<List<_i7.Event>>);

  @override
  List<_i7.Event> filterMyEventsByKind(
    List<_i7.Event>? events,
    List<int>? kinds,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#filterMyEventsByKind, [events, kinds]),
            returnValue: <_i7.Event>[],
          )
          as List<_i7.Event>);

  @override
  Map<String, _i7.Event> filterMyParameterizedEvents(
    List<_i7.Event>? events,
    List<int>? kinds,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#filterMyParameterizedEvents, [events, kinds]),
            returnValue: <String, _i7.Event>{},
          )
          as Map<String, _i7.Event>);
}
