// Mocks generated by Mockito 5.4.6 from annotations
// in openvine/test/widgets/share_video_menu_comprehensive_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;

import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i9;
import 'package:nostr_sdk/event.dart' as _i7;
import 'package:openvine/models/video_event.dart' as _i6;
import 'package:openvine/services/content_deletion_service.dart' as _i2;
import 'package:openvine/services/content_moderation_service.dart' as _i3;
import 'package:openvine/services/curated_list_service.dart' as _i8;
import 'package:openvine/services/social_service.dart' as _i10;
import 'package:openvine/services/video_sharing_service.dart' as _i4;
import 'package:share_plus/share_plus.dart' as _i11;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeDeleteResult_0 extends _i1.SmartFake implements _i2.DeleteResult {
  _FakeDeleteResult_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeModerationResult_1 extends _i1.SmartFake
    implements _i3.ModerationResult {
  _FakeModerationResult_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeShareResult_2 extends _i1.SmartFake implements _i4.ShareResult {
  _FakeShareResult_2(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [ContentDeletionService].
///
/// See the documentation for Mockito's code generation for more information.
class MockContentDeletionService extends _i1.Mock
    implements _i2.ContentDeletionService {
  @override
  List<_i2.ContentDeletion> get deletionHistory =>
      (super.noSuchMethod(
            Invocation.getter(#deletionHistory),
            returnValue: <_i2.ContentDeletion>[],
            returnValueForMissingStub: <_i2.ContentDeletion>[],
          )
          as List<_i2.ContentDeletion>);

  @override
  bool get isInitialized =>
      (super.noSuchMethod(
            Invocation.getter(#isInitialized),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  _i5.Future<void> initialize() =>
      (super.noSuchMethod(
            Invocation.method(#initialize, []),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<_i2.DeleteResult> deleteContent({
    required _i6.VideoEvent? video,
    required String? reason,
    String? additionalContext,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#deleteContent, [], {
              #video: video,
              #reason: reason,
              #additionalContext: additionalContext,
            }),
            returnValue: _i5.Future<_i2.DeleteResult>.value(
              _FakeDeleteResult_0(
                this,
                Invocation.method(#deleteContent, [], {
                  #video: video,
                  #reason: reason,
                  #additionalContext: additionalContext,
                }),
              ),
            ),
            returnValueForMissingStub: _i5.Future<_i2.DeleteResult>.value(
              _FakeDeleteResult_0(
                this,
                Invocation.method(#deleteContent, [], {
                  #video: video,
                  #reason: reason,
                  #additionalContext: additionalContext,
                }),
              ),
            ),
          )
          as _i5.Future<_i2.DeleteResult>);

  @override
  _i5.Future<_i2.DeleteResult> quickDelete({
    required _i6.VideoEvent? video,
    required _i2.DeleteReason? reason,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#quickDelete, [], {
              #video: video,
              #reason: reason,
            }),
            returnValue: _i5.Future<_i2.DeleteResult>.value(
              _FakeDeleteResult_0(
                this,
                Invocation.method(#quickDelete, [], {
                  #video: video,
                  #reason: reason,
                }),
              ),
            ),
            returnValueForMissingStub: _i5.Future<_i2.DeleteResult>.value(
              _FakeDeleteResult_0(
                this,
                Invocation.method(#quickDelete, [], {
                  #video: video,
                  #reason: reason,
                }),
              ),
            ),
          )
          as _i5.Future<_i2.DeleteResult>);

  @override
  bool hasBeenDeleted(String? eventId) =>
      (super.noSuchMethod(
            Invocation.method(#hasBeenDeleted, [eventId]),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  _i2.ContentDeletion? getDeletionForEvent(String? eventId) =>
      (super.noSuchMethod(
            Invocation.method(#getDeletionForEvent, [eventId]),
            returnValueForMissingStub: null,
          )
          as _i2.ContentDeletion?);

  @override
  _i5.Future<void> clearOldDeletions({
    Duration? maxAge = const Duration(days: 90),
  }) =>
      (super.noSuchMethod(
            Invocation.method(#clearOldDeletions, [], {#maxAge: maxAge}),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  void dispose() => super.noSuchMethod(
    Invocation.method(#dispose, []),
    returnValueForMissingStub: null,
  );
}

/// A class which mocks [ContentModerationService].
///
/// See the documentation for Mockito's code generation for more information.
class MockContentModerationService extends _i1.Mock
    implements _i3.ContentModerationService {
  @override
  bool get enableDefaultModeration =>
      (super.noSuchMethod(
            Invocation.getter(#enableDefaultModeration),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  bool get enableCustomMuteLists =>
      (super.noSuchMethod(
            Invocation.getter(#enableCustomMuteLists),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  bool get showContentWarnings =>
      (super.noSuchMethod(
            Invocation.getter(#showContentWarnings),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  _i3.ContentSeverity get autoHideLevel =>
      (super.noSuchMethod(
            Invocation.getter(#autoHideLevel),
            returnValue: _i3.ContentSeverity.info,
            returnValueForMissingStub: _i3.ContentSeverity.info,
          )
          as _i3.ContentSeverity);

  @override
  List<String> get subscribedLists =>
      (super.noSuchMethod(
            Invocation.getter(#subscribedLists),
            returnValue: <String>[],
            returnValueForMissingStub: <String>[],
          )
          as List<String>);

  @override
  _i5.Future<void> initialize() =>
      (super.noSuchMethod(
            Invocation.method(#initialize, []),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i3.ModerationResult checkContent(_i7.Event? event) =>
      (super.noSuchMethod(
            Invocation.method(#checkContent, [event]),
            returnValue: _FakeModerationResult_1(
              this,
              Invocation.method(#checkContent, [event]),
            ),
            returnValueForMissingStub: _FakeModerationResult_1(
              this,
              Invocation.method(#checkContent, [event]),
            ),
          )
          as _i3.ModerationResult);

  @override
  _i5.Future<void> addToMuteList({
    required String? type,
    required String? value,
    required _i3.ContentFilterReason? reason,
    _i3.ContentSeverity? severity = _i3.ContentSeverity.hide,
    String? note,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#addToMuteList, [], {
              #type: type,
              #value: value,
              #reason: reason,
              #severity: severity,
              #note: note,
            }),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<void> removeFromMuteList(String? type, String? value) =>
      (super.noSuchMethod(
            Invocation.method(#removeFromMuteList, [type, value]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<void> blockUser(String? pubkey, {String? reason}) =>
      (super.noSuchMethod(
            Invocation.method(#blockUser, [pubkey], {#reason: reason}),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<void> muteKeyword(
    String? keyword,
    _i3.ContentSeverity? severity,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#muteKeyword, [keyword, severity]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<void> subscribeToMuteList(String? listId) =>
      (super.noSuchMethod(
            Invocation.method(#subscribeToMuteList, [listId]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<void> unsubscribeFromMuteList(String? listId) =>
      (super.noSuchMethod(
            Invocation.method(#unsubscribeFromMuteList, [listId]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<void> updateSettings({
    bool? enableDefaultModeration,
    bool? enableCustomMuteLists,
    bool? showContentWarnings,
    _i3.ContentSeverity? autoHideLevel,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#updateSettings, [], {
              #enableDefaultModeration: enableDefaultModeration,
              #enableCustomMuteLists: enableCustomMuteLists,
              #showContentWarnings: showContentWarnings,
              #autoHideLevel: autoHideLevel,
            }),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  Map<String, dynamic> getModerationStats() =>
      (super.noSuchMethod(
            Invocation.method(#getModerationStats, []),
            returnValue: <String, dynamic>{},
            returnValueForMissingStub: <String, dynamic>{},
          )
          as Map<String, dynamic>);

  @override
  void dispose() => super.noSuchMethod(
    Invocation.method(#dispose, []),
    returnValueForMissingStub: null,
  );
}

/// A class which mocks [CuratedListService].
///
/// See the documentation for Mockito's code generation for more information.
class MockCuratedListService extends _i1.Mock
    implements _i8.CuratedListService {
  @override
  List<_i8.CuratedList> get lists =>
      (super.noSuchMethod(
            Invocation.getter(#lists),
            returnValue: <_i8.CuratedList>[],
            returnValueForMissingStub: <_i8.CuratedList>[],
          )
          as List<_i8.CuratedList>);

  @override
  bool get isInitialized =>
      (super.noSuchMethod(
            Invocation.getter(#isInitialized),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  _i5.Future<void> initialize() =>
      (super.noSuchMethod(
            Invocation.method(#initialize, []),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  bool hasDefaultList() =>
      (super.noSuchMethod(
            Invocation.method(#hasDefaultList, []),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  _i5.Future<_i8.CuratedList?> createList({
    required String? name,
    String? description,
    String? imageUrl,
    bool? isPublic = true,
    List<String>? tags = const [],
    bool? isCollaborative = false,
    List<String>? allowedCollaborators = const [],
    String? thumbnailEventId,
    _i8.PlayOrder? playOrder = _i8.PlayOrder.chronological,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#createList, [], {
              #name: name,
              #description: description,
              #imageUrl: imageUrl,
              #isPublic: isPublic,
              #tags: tags,
              #isCollaborative: isCollaborative,
              #allowedCollaborators: allowedCollaborators,
              #thumbnailEventId: thumbnailEventId,
              #playOrder: playOrder,
            }),
            returnValue: _i5.Future<_i8.CuratedList?>.value(),
            returnValueForMissingStub: _i5.Future<_i8.CuratedList?>.value(),
          )
          as _i5.Future<_i8.CuratedList?>);

  @override
  _i5.Future<bool> addVideoToList(String? listId, String? videoEventId) =>
      (super.noSuchMethod(
            Invocation.method(#addVideoToList, [listId, videoEventId]),
            returnValue: _i5.Future<bool>.value(false),
            returnValueForMissingStub: _i5.Future<bool>.value(false),
          )
          as _i5.Future<bool>);

  @override
  _i5.Future<bool> removeVideoFromList(String? listId, String? videoEventId) =>
      (super.noSuchMethod(
            Invocation.method(#removeVideoFromList, [listId, videoEventId]),
            returnValue: _i5.Future<bool>.value(false),
            returnValueForMissingStub: _i5.Future<bool>.value(false),
          )
          as _i5.Future<bool>);

  @override
  bool isVideoInList(String? listId, String? videoEventId) =>
      (super.noSuchMethod(
            Invocation.method(#isVideoInList, [listId, videoEventId]),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  bool isVideoInDefaultList(String? videoEventId) =>
      (super.noSuchMethod(
            Invocation.method(#isVideoInDefaultList, [videoEventId]),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  _i8.CuratedList? getListById(String? listId) =>
      (super.noSuchMethod(
            Invocation.method(#getListById, [listId]),
            returnValueForMissingStub: null,
          )
          as _i8.CuratedList?);

  @override
  _i5.Future<bool> updateList({
    required String? listId,
    String? name,
    String? description,
    String? imageUrl,
    bool? isPublic,
    List<String>? tags,
    bool? isCollaborative,
    List<String>? allowedCollaborators,
    String? thumbnailEventId,
    _i8.PlayOrder? playOrder,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#updateList, [], {
              #listId: listId,
              #name: name,
              #description: description,
              #imageUrl: imageUrl,
              #isPublic: isPublic,
              #tags: tags,
              #isCollaborative: isCollaborative,
              #allowedCollaborators: allowedCollaborators,
              #thumbnailEventId: thumbnailEventId,
              #playOrder: playOrder,
            }),
            returnValue: _i5.Future<bool>.value(false),
            returnValueForMissingStub: _i5.Future<bool>.value(false),
          )
          as _i5.Future<bool>);

  @override
  _i5.Future<bool> deleteList(String? listId) =>
      (super.noSuchMethod(
            Invocation.method(#deleteList, [listId]),
            returnValue: _i5.Future<bool>.value(false),
            returnValueForMissingStub: _i5.Future<bool>.value(false),
          )
          as _i5.Future<bool>);

  @override
  _i5.Future<bool> reorderVideos(String? listId, List<String>? newOrder) =>
      (super.noSuchMethod(
            Invocation.method(#reorderVideos, [listId, newOrder]),
            returnValue: _i5.Future<bool>.value(false),
            returnValueForMissingStub: _i5.Future<bool>.value(false),
          )
          as _i5.Future<bool>);

  @override
  List<String> getOrderedVideoIds(String? listId) =>
      (super.noSuchMethod(
            Invocation.method(#getOrderedVideoIds, [listId]),
            returnValue: <String>[],
            returnValueForMissingStub: <String>[],
          )
          as List<String>);

  @override
  _i5.Future<bool> addCollaborator(String? listId, String? pubkey) =>
      (super.noSuchMethod(
            Invocation.method(#addCollaborator, [listId, pubkey]),
            returnValue: _i5.Future<bool>.value(false),
            returnValueForMissingStub: _i5.Future<bool>.value(false),
          )
          as _i5.Future<bool>);

  @override
  _i5.Future<bool> removeCollaborator(String? listId, String? pubkey) =>
      (super.noSuchMethod(
            Invocation.method(#removeCollaborator, [listId, pubkey]),
            returnValue: _i5.Future<bool>.value(false),
            returnValueForMissingStub: _i5.Future<bool>.value(false),
          )
          as _i5.Future<bool>);

  @override
  bool canCollaborate(String? listId, String? pubkey) =>
      (super.noSuchMethod(
            Invocation.method(#canCollaborate, [listId, pubkey]),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  List<_i8.CuratedList> getListsByTag(String? tag) =>
      (super.noSuchMethod(
            Invocation.method(#getListsByTag, [tag]),
            returnValue: <_i8.CuratedList>[],
            returnValueForMissingStub: <_i8.CuratedList>[],
          )
          as List<_i8.CuratedList>);

  @override
  List<String> getAllTags() =>
      (super.noSuchMethod(
            Invocation.method(#getAllTags, []),
            returnValue: <String>[],
            returnValueForMissingStub: <String>[],
          )
          as List<String>);

  @override
  List<_i8.CuratedList> searchLists(String? query) =>
      (super.noSuchMethod(
            Invocation.method(#searchLists, [query]),
            returnValue: <_i8.CuratedList>[],
            returnValueForMissingStub: <_i8.CuratedList>[],
          )
          as List<_i8.CuratedList>);

  @override
  List<_i8.CuratedList> getListsContainingVideo(String? videoEventId) =>
      (super.noSuchMethod(
            Invocation.method(#getListsContainingVideo, [videoEventId]),
            returnValue: <_i8.CuratedList>[],
            returnValueForMissingStub: <_i8.CuratedList>[],
          )
          as List<_i8.CuratedList>);

  @override
  String getVideoListSummary(String? videoEventId) =>
      (super.noSuchMethod(
            Invocation.method(#getVideoListSummary, [videoEventId]),
            returnValue: _i9.dummyValue<String>(
              this,
              Invocation.method(#getVideoListSummary, [videoEventId]),
            ),
            returnValueForMissingStub: _i9.dummyValue<String>(
              this,
              Invocation.method(#getVideoListSummary, [videoEventId]),
            ),
          )
          as String);

  @override
  _i5.Future<void> fetchUserListsFromRelays() =>
      (super.noSuchMethod(
            Invocation.method(#fetchUserListsFromRelays, []),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);
}

/// A class which mocks [SocialService].
///
/// See the documentation for Mockito's code generation for more information.
class MockSocialService extends _i1.Mock implements _i10.SocialService {
  @override
  Set<String> get likedEventIds =>
      (super.noSuchMethod(
            Invocation.getter(#likedEventIds),
            returnValue: <String>{},
            returnValueForMissingStub: <String>{},
          )
          as Set<String>);

  @override
  List<String> get followingPubkeys =>
      (super.noSuchMethod(
            Invocation.getter(#followingPubkeys),
            returnValue: <String>[],
            returnValueForMissingStub: <String>[],
          )
          as List<String>);

  @override
  List<_i10.FollowSet> get followSets =>
      (super.noSuchMethod(
            Invocation.getter(#followSets),
            returnValue: <_i10.FollowSet>[],
            returnValueForMissingStub: <_i10.FollowSet>[],
          )
          as List<_i10.FollowSet>);

  @override
  bool isLiked(String? eventId) =>
      (super.noSuchMethod(
            Invocation.method(#isLiked, [eventId]),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  bool hasReposted(String? eventId, {String? pubkey, String? dTag}) =>
      (super.noSuchMethod(
            Invocation.method(
              #hasReposted,
              [eventId],
              {#pubkey: pubkey, #dTag: dTag},
            ),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  int? getCachedLikeCount(String? eventId) =>
      (super.noSuchMethod(
            Invocation.method(#getCachedLikeCount, [eventId]),
            returnValueForMissingStub: null,
          )
          as int?);

  @override
  bool isFollowing(String? pubkey) =>
      (super.noSuchMethod(
            Invocation.method(#isFollowing, [pubkey]),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  Map<String, int>? getCachedFollowerStats(String? pubkey) =>
      (super.noSuchMethod(
            Invocation.method(#getCachedFollowerStats, [pubkey]),
            returnValueForMissingStub: null,
          )
          as Map<String, int>?);

  @override
  _i10.FollowSet? getFollowSetById(String? setId) =>
      (super.noSuchMethod(
            Invocation.method(#getFollowSetById, [setId]),
            returnValueForMissingStub: null,
          )
          as _i10.FollowSet?);

  @override
  bool isInFollowSet(String? setId, String? pubkey) =>
      (super.noSuchMethod(
            Invocation.method(#isInFollowSet, [setId, pubkey]),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  _i5.Future<void> toggleLike(String? eventId, String? authorPubkey) =>
      (super.noSuchMethod(
            Invocation.method(#toggleLike, [eventId, authorPubkey]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<Map<String, dynamic>> getLikeStatus(String? eventId) =>
      (super.noSuchMethod(
            Invocation.method(#getLikeStatus, [eventId]),
            returnValue: _i5.Future<Map<String, dynamic>>.value(
              <String, dynamic>{},
            ),
            returnValueForMissingStub: _i5.Future<Map<String, dynamic>>.value(
              <String, dynamic>{},
            ),
          )
          as _i5.Future<Map<String, dynamic>>);

  @override
  _i5.Future<List<_i7.Event>> fetchLikedEvents(String? pubkey) =>
      (super.noSuchMethod(
            Invocation.method(#fetchLikedEvents, [pubkey]),
            returnValue: _i5.Future<List<_i7.Event>>.value(<_i7.Event>[]),
            returnValueForMissingStub: _i5.Future<List<_i7.Event>>.value(
              <_i7.Event>[],
            ),
          )
          as _i5.Future<List<_i7.Event>>);

  @override
  _i5.Future<void> fetchCurrentUserFollowList() =>
      (super.noSuchMethod(
            Invocation.method(#fetchCurrentUserFollowList, []),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<void> followUser(String? pubkeyToFollow) =>
      (super.noSuchMethod(
            Invocation.method(#followUser, [pubkeyToFollow]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<void> unfollowUser(String? pubkeyToUnfollow) =>
      (super.noSuchMethod(
            Invocation.method(#unfollowUser, [pubkeyToUnfollow]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<Map<String, int>> getFollowerStats(String? pubkey) =>
      (super.noSuchMethod(
            Invocation.method(#getFollowerStats, [pubkey]),
            returnValue: _i5.Future<Map<String, int>>.value(<String, int>{}),
            returnValueForMissingStub: _i5.Future<Map<String, int>>.value(
              <String, int>{},
            ),
          )
          as _i5.Future<Map<String, int>>);

  @override
  _i5.Future<_i10.FollowSet?> createFollowSet({
    required String? name,
    String? description,
    String? imageUrl,
    List<String>? initialPubkeys = const [],
  }) =>
      (super.noSuchMethod(
            Invocation.method(#createFollowSet, [], {
              #name: name,
              #description: description,
              #imageUrl: imageUrl,
              #initialPubkeys: initialPubkeys,
            }),
            returnValue: _i5.Future<_i10.FollowSet?>.value(),
            returnValueForMissingStub: _i5.Future<_i10.FollowSet?>.value(),
          )
          as _i5.Future<_i10.FollowSet?>);

  @override
  _i5.Future<bool> addToFollowSet(String? setId, String? pubkey) =>
      (super.noSuchMethod(
            Invocation.method(#addToFollowSet, [setId, pubkey]),
            returnValue: _i5.Future<bool>.value(false),
            returnValueForMissingStub: _i5.Future<bool>.value(false),
          )
          as _i5.Future<bool>);

  @override
  _i5.Future<bool> removeFromFollowSet(String? setId, String? pubkey) =>
      (super.noSuchMethod(
            Invocation.method(#removeFromFollowSet, [setId, pubkey]),
            returnValue: _i5.Future<bool>.value(false),
            returnValueForMissingStub: _i5.Future<bool>.value(false),
          )
          as _i5.Future<bool>);

  @override
  _i5.Future<bool> updateFollowSet({
    required String? setId,
    String? name,
    String? description,
    String? imageUrl,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#updateFollowSet, [], {
              #setId: setId,
              #name: name,
              #description: description,
              #imageUrl: imageUrl,
            }),
            returnValue: _i5.Future<bool>.value(false),
            returnValueForMissingStub: _i5.Future<bool>.value(false),
          )
          as _i5.Future<bool>);

  @override
  _i5.Future<bool> deleteFollowSet(String? setId) =>
      (super.noSuchMethod(
            Invocation.method(#deleteFollowSet, [setId]),
            returnValue: _i5.Future<bool>.value(false),
            returnValueForMissingStub: _i5.Future<bool>.value(false),
          )
          as _i5.Future<bool>);

  @override
  _i5.Future<int> getUserVideoCount(String? pubkey) =>
      (super.noSuchMethod(
            Invocation.method(#getUserVideoCount, [pubkey]),
            returnValue: _i5.Future<int>.value(0),
            returnValueForMissingStub: _i5.Future<int>.value(0),
          )
          as _i5.Future<int>);

  @override
  _i5.Future<int> getUserTotalLikes(String? pubkey) =>
      (super.noSuchMethod(
            Invocation.method(#getUserTotalLikes, [pubkey]),
            returnValue: _i5.Future<int>.value(0),
            returnValueForMissingStub: _i5.Future<int>.value(0),
          )
          as _i5.Future<int>);

  @override
  _i5.Future<void> postComment({
    required String? content,
    required String? rootEventId,
    required String? rootEventAuthorPubkey,
    String? replyToEventId,
    String? replyToAuthorPubkey,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#postComment, [], {
              #content: content,
              #rootEventId: rootEventId,
              #rootEventAuthorPubkey: rootEventAuthorPubkey,
              #replyToEventId: replyToEventId,
              #replyToAuthorPubkey: replyToAuthorPubkey,
            }),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Stream<_i7.Event> fetchCommentsForEvent(String? rootEventId) =>
      (super.noSuchMethod(
            Invocation.method(#fetchCommentsForEvent, [rootEventId]),
            returnValue: _i5.Stream<_i7.Event>.empty(),
            returnValueForMissingStub: _i5.Stream<_i7.Event>.empty(),
          )
          as _i5.Stream<_i7.Event>);

  @override
  _i5.Future<int> getCommentCount(String? rootEventId) =>
      (super.noSuchMethod(
            Invocation.method(#getCommentCount, [rootEventId]),
            returnValue: _i5.Future<int>.value(0),
            returnValueForMissingStub: _i5.Future<int>.value(0),
          )
          as _i5.Future<int>);

  @override
  _i5.Future<void> cancelCommentSubscriptions(String? rootEventId) =>
      (super.noSuchMethod(
            Invocation.method(#cancelCommentSubscriptions, [rootEventId]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<void> repostEvent(_i7.Event? eventToRepost) =>
      (super.noSuchMethod(
            Invocation.method(#repostEvent, [eventToRepost]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<void> publishRightToBeForgotten() =>
      (super.noSuchMethod(
            Invocation.method(#publishRightToBeForgotten, []),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  void dispose() => super.noSuchMethod(
    Invocation.method(#dispose, []),
    returnValueForMissingStub: null,
  );
}

/// A class which mocks [VideoSharingService].
///
/// See the documentation for Mockito's code generation for more information.
class MockVideoSharingService extends _i1.Mock
    implements _i4.VideoSharingService {
  @override
  List<_i4.ShareableUser> get recentlySharedWith =>
      (super.noSuchMethod(
            Invocation.getter(#recentlySharedWith),
            returnValue: <_i4.ShareableUser>[],
            returnValueForMissingStub: <_i4.ShareableUser>[],
          )
          as List<_i4.ShareableUser>);

  @override
  _i5.Future<_i4.ShareResult> shareVideoWithUser({
    required _i6.VideoEvent? video,
    required String? recipientPubkey,
    String? personalMessage,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#shareVideoWithUser, [], {
              #video: video,
              #recipientPubkey: recipientPubkey,
              #personalMessage: personalMessage,
            }),
            returnValue: _i5.Future<_i4.ShareResult>.value(
              _FakeShareResult_2(
                this,
                Invocation.method(#shareVideoWithUser, [], {
                  #video: video,
                  #recipientPubkey: recipientPubkey,
                  #personalMessage: personalMessage,
                }),
              ),
            ),
            returnValueForMissingStub: _i5.Future<_i4.ShareResult>.value(
              _FakeShareResult_2(
                this,
                Invocation.method(#shareVideoWithUser, [], {
                  #video: video,
                  #recipientPubkey: recipientPubkey,
                  #personalMessage: personalMessage,
                }),
              ),
            ),
          )
          as _i5.Future<_i4.ShareResult>);

  @override
  _i5.Future<Map<String, _i4.ShareResult>> shareVideoWithMultipleUsers({
    required _i6.VideoEvent? video,
    required List<String>? recipientPubkeys,
    String? personalMessage,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#shareVideoWithMultipleUsers, [], {
              #video: video,
              #recipientPubkeys: recipientPubkeys,
              #personalMessage: personalMessage,
            }),
            returnValue: _i5.Future<Map<String, _i4.ShareResult>>.value(
              <String, _i4.ShareResult>{},
            ),
            returnValueForMissingStub:
                _i5.Future<Map<String, _i4.ShareResult>>.value(
                  <String, _i4.ShareResult>{},
                ),
          )
          as _i5.Future<Map<String, _i4.ShareResult>>);

  @override
  _i5.Future<List<_i4.ShareableUser>> getShareableUsers({int? limit = 20}) =>
      (super.noSuchMethod(
            Invocation.method(#getShareableUsers, [], {#limit: limit}),
            returnValue: _i5.Future<List<_i4.ShareableUser>>.value(
              <_i4.ShareableUser>[],
            ),
            returnValueForMissingStub:
                _i5.Future<List<_i4.ShareableUser>>.value(
                  <_i4.ShareableUser>[],
                ),
          )
          as _i5.Future<List<_i4.ShareableUser>>);

  @override
  _i5.Future<List<_i4.ShareableUser>> searchUsersToShareWith(String? query) =>
      (super.noSuchMethod(
            Invocation.method(#searchUsersToShareWith, [query]),
            returnValue: _i5.Future<List<_i4.ShareableUser>>.value(
              <_i4.ShareableUser>[],
            ),
            returnValueForMissingStub:
                _i5.Future<List<_i4.ShareableUser>>.value(
                  <_i4.ShareableUser>[],
                ),
          )
          as _i5.Future<List<_i4.ShareableUser>>);

  @override
  String generateShareUrl(_i6.VideoEvent? video) =>
      (super.noSuchMethod(
            Invocation.method(#generateShareUrl, [video]),
            returnValue: _i9.dummyValue<String>(
              this,
              Invocation.method(#generateShareUrl, [video]),
            ),
            returnValueForMissingStub: _i9.dummyValue<String>(
              this,
              Invocation.method(#generateShareUrl, [video]),
            ),
          )
          as String);

  @override
  String generateShareText(_i6.VideoEvent? video) =>
      (super.noSuchMethod(
            Invocation.method(#generateShareText, [video]),
            returnValue: _i9.dummyValue<String>(
              this,
              Invocation.method(#generateShareText, [video]),
            ),
            returnValueForMissingStub: _i9.dummyValue<String>(
              this,
              Invocation.method(#generateShareText, [video]),
            ),
          )
          as String);

  @override
  bool hasSharedWithRecently(String? pubkey) =>
      (super.noSuchMethod(
            Invocation.method(#hasSharedWithRecently, [pubkey]),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  Map<String, dynamic> getSharingStats() =>
      (super.noSuchMethod(
            Invocation.method(#getSharingStats, []),
            returnValue: <String, dynamic>{},
            returnValueForMissingStub: <String, dynamic>{},
          )
          as Map<String, dynamic>);

  @override
  void clearSharingHistory() => super.noSuchMethod(
    Invocation.method(#clearSharingHistory, []),
    returnValueForMissingStub: null,
  );
}

/// A class which mocks [Share].
///
/// See the documentation for Mockito's code generation for more information.
class MockShare extends _i1.Mock implements _i11.Share {}
